{
  "type": "record",
  "name": "AddressDTO",
  "namespace": "net.wowdev.microservice.ecommerce.dto",
  "doc": "Schema representing a physical shipping or billing address.",
  "fields": [
    {
      "name": "id",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "addressLine1",
      "type": "string",
      "doc": "Street address, P.O. box, or company name."
    },
    {
      "name": "addressLine2",
      "type": "string",
      "doc": "Apartment, suite, unit, building, or floor."
    },
    {
      "name": "city",
      "type": "string"
    },
    {
      "name": "stateProvince",
      "type": "string",
      "doc": "State, province, region, or territory."
    },
    {
      "name": "postalCode",
      "type": "string"
    },
    {
      "name": "country",
      "type": "string",
      "doc": "Full country name or standard ISO 3166-1 alpha-2 code."
    },
    {
      "name": "createdAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "modifiedAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    }
  ]
}
