{
  "type": "record",
  "name": "OrderLineDTO",
  "namespace": "net.wowdev.microservice.ecommerce.dto",
  "doc": "Individual item detail within the order.",
  "fields": [
    {
      "name": "id",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "product",
      "type": "net.wowdev.microservice.ecommerce.dto.ProductDTO",
      "doc": "Unique identifier for the product."
    },
    {
      "name": "quantity",
      "type": "int",
      "doc": "Quantity of the product purchased."
    },
    {
      "name": "price",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 10,
        "scale": 2
      },
      "doc": "Price per unit utilizing the decimal logical type."
    },
    {
      "name": "lineAmount",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 19,
        "scale": 2
      }
    }
  ]
}
