{
  "type": "record",
  "name": "PaymentDTO",
  "namespace": "net.wowdev.microservice.ecommerce.dto",
  "fields": [
    {
      "name": "id",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "transactionId",
      "type": "string"
    },
    {
      "name": "amount",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 19,
        "scale": 2
      }
    },
    {
      "name": "currency",
      "type": "string"
    },
    {
      "name": "paymentMethod",
      "type": {
        "type": "enum",
        "name": "PaymentMethod",
        "symbols": [
          "CREDIT_CARD",
          "DEBIT_CARD",
          "PIX",
          "PAYPAL"
        ]
      }
    },
    {
      "name": "status",
      "type": {
        "type": "enum",
        "name": "PaymentStatus",
        "symbols": [
          "PENDING",
          "AUTHORIZED",
          "COMPLETED",
          "REJECTED",
          "FAILED"
        ]
      }
    }
  ]
}
